version: '3.8'

services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpasswrod
      POSTGRES_DB: reservation
    ports:
      - "5432:5432"
    volumes:
      - .docker/pg_data:/var/lib/postgresql/data